//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using UnityEngine;

namespace SeanLib.Core
{
    public static class StringHelper
    {
        /// <summary>
        /// 用制定的拼接符拼接字符串
        /// </summary>
        /// <param name="src"></param>
        /// <param name="separator">拼接符</param>
        /// <returns></returns>
        public static string Joint(this string[] src, string separator)
        {
            string str = "";
            for (int i = 0; i < src.Length; i++)
            {
                str += src[i] + separator;
            }
            if (str.Length > 0)
                return str.Substring(0, str.Length - 1);
            return str;
        }

        /// <summary>
        /// where string like 15.21,548,157
        /// </summary>
        /// <returns></returns>
        public static Vector3 GetVector3FromString(string str)
        {
            Vector3 v;
            string[] strings = str.Split(',');
            v.x = (float)Convert.ToDouble(strings[0]);
            v.y = (float)Convert.ToDouble(strings[1]);
            v.z = (float)Convert.ToDouble(strings[2]);
            return v;
        }

        /// <summary>
        /// where string like 15.21,548,157
        /// </summary>
        /// <returns></returns>
        public static Quaternion GetQuaternionFromString(string str)
        {
            Quaternion v = new Quaternion();
            Vector3 vector3FromString = GetVector3FromString(str);
            v.eulerAngles = vector3FromString;
            return v;
        }
    }


}

